const enMessage = {
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  MOBILE_NUMBER_ALREADY_EXISTS: "MOBILE_NUMBER_ALREADY_EXISTS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  OTP_SENT: "OTP_SENT",
  OTP_VERIFIED: "OTP_VERIFIED",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_WRONG: "OTP_WRONG",
  OTP_NOT_MATCHED: "OTP_NOT_MATCHED",
  PROFILE_STEP_1_COMPLETED: "PROFILE_STEP_1_COMPLETED",
  PROFILE_STEP_2_COMPLETED: "PROFILE_STEP_2_COMPLETED",
  PROFILE_STEP_3_COMPLETED: "PROFILE_STEP_3_COMPLETED",
  PROFILE_STEP_4_COMPLETED: "PROFILE_STEP_4_COMPLETED",
};

module.exports = {
  enMessage,
};
